name: AI Platform CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [gateway, text-gen, sentiment-analyzer, embeddings-service]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f services/${{ matrix.service }}/requirements.txt ]; then
          pip install -r services/${{ matrix.service }}/requirements.txt
        elif [ -f ${{ matrix.service }}/requirements.txt ]; then
          pip install -r ${{ matrix.service }}/requirements.txt
        fi
        pip install pytest
    
    - name: Test with pytest
      run: |
        # Add tests when they are created
        echo "Tests will run here for ${{ matrix.service }}"
        # pytest services/${{ matrix.service }}/tests/

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [gateway, text-gen, sentiment-analyzer, embeddings-service]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ matrix.service == 'gateway' && './' || './services/' }}${{ matrix.service }}
        push: false
        tags: ai-platform/${{ matrix.service }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
